package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"tsunagu/backend/internal/api/graph/model"
	"tsunagu/backend/internal/sandbox"
	sandboxv1 "tsunagu/backend/internal/sandbox/gen/sandbox/v1"
)

// Chapters is the resolver for the chapters field.
func (r *libraryEntryResolver) Chapters(ctx context.Context, obj *model.LibraryEntry) ([]*model.Chapter, error) {
	id, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	chapters, err := r.Sy.SyncChapters(ctx, c, id)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Chapter, 0, len(chapters))
	for _, ch := range chapters {
		out = append(out, toChapter(ch))
	}
	return out, nil
}

// ReadingProgress is the resolver for the readingProgress field.
func (r *libraryEntryResolver) ReadingProgress(ctx context.Context, obj *model.LibraryEntry) ([]*model.ReadingProgress, error) {
	id, err := parseID(obj.ID)
	if err != nil {
		return nil, err
	}
	list, err := r.Sy.ListReadingProgress(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ReadingProgress, 0, len(list))
	for _, p := range list {
		out = append(out, toReadingProgress(p))
	}
	return out, nil
}

// AddRepository is the resolver for the addRepository field.
func (r *mutationResolver) AddRepository(ctx context.Context, indexURL string, name *string) (*model.Repository, error) {
	n := ""
	if name != nil {
		n = *name
	}
	repo, err := r.Sy.AddRepository(ctx, indexURL, n)
	if err != nil {
		return nil, err
	}
	return toRepository(repo), nil
}

// RenameRepository is the resolver for the renameRepository field.
func (r *mutationResolver) RenameRepository(ctx context.Context, repositoryID string, name string) (*model.Repository, error) {
	id, err := parseID(repositoryID)
	if err != nil {
		return nil, err
	}
	repo, err := r.Sy.RenameRepository(ctx, id, name)
	if err != nil {
		return nil, err
	}
	return toRepository(repo), nil
}

// DeleteRepository is the resolver for the deleteRepository field.
func (r *mutationResolver) DeleteRepository(ctx context.Context, repositoryID string) (bool, error) {
	id, err := parseID(repositoryID)
	if err != nil {
		return false, err
	}
	if err := r.Sy.DeleteRepository(ctx, id); err != nil {
		return false, err
	}
	return true, nil
}

// InstallExtension is the resolver for the installExtension field.
func (r *mutationResolver) InstallExtension(ctx context.Context, packageName string) (*model.Extension, error) {
	ext, err := r.Sy.InstallExtension(ctx, packageName)
	if err != nil {
		return nil, err
	}
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	if _, err := c.LoadExtensions(ctx, []*sandboxv1.ExtensionToLoad{{
		ExtensionId: ext.PackageName,
		JarPath:     ext.JarPath.String,
		ContentType: sandbox.ContentTypeToProto(ext.ContentType),
		Lang:        ext.Lang,
	}}); err != nil {
		return nil, err
	}
	return toExtension(ext), nil
}

// UninstallExtension is the resolver for the uninstallExtension field.
func (r *mutationResolver) UninstallExtension(ctx context.Context, packageName string) (*model.Extension, error) {
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	if _, err := c.UnloadExtension(ctx, packageName); err != nil {
		return nil, err
	}
	ext, err := r.Sy.UninstallExtension(ctx, packageName)
	if err != nil {
		return nil, err
	}
	return toExtension(ext), nil
}

// UpdateExtension is the resolver for the updateExtension field.
func (r *mutationResolver) UpdateExtension(ctx context.Context, packageName string) (*model.Extension, error) {
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	if _, err := c.UnloadExtension(ctx, packageName); err != nil {
		return nil, err
	}
	ext, err := r.Sy.UpdateExtension(ctx, packageName)
	if err != nil {
		return nil, err
	}
	if _, err := c.LoadExtensions(ctx, []*sandboxv1.ExtensionToLoad{{
		ExtensionId: ext.PackageName,
		JarPath:     ext.JarPath.String,
		ContentType: sandbox.ContentTypeToProto(ext.ContentType),
		Lang:        ext.Lang,
	}}); err != nil {
		return nil, err
	}
	return toExtension(ext), nil
}

// AddToLibrary is the resolver for the addToLibrary field.
func (r *mutationResolver) AddToLibrary(ctx context.Context, extensionID string, sourceEntryID string) (*model.LibraryEntry, error) {
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	entry, err := r.Sy.AddToLibrary(ctx, c, extensionID, sourceEntryID)
	if err != nil {
		return nil, err
	}
	return toLibraryEntry(entry), nil
}

// SyncChapters is the resolver for the syncChapters field.
func (r *mutationResolver) SyncChapters(ctx context.Context, libraryEntryID string) ([]*model.Chapter, error) {
	id, err := parseID(libraryEntryID)
	if err != nil {
		return nil, err
	}
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	chapters, err := r.Sy.SyncChapters(ctx, c, id)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Chapter, 0, len(chapters))
	for _, ch := range chapters {
		out = append(out, toChapter(ch))
	}
	return out, nil
}

// UpdateReadingProgress is the resolver for the updateReadingProgress field.
func (r *mutationResolver) UpdateReadingProgress(ctx context.Context, libraryEntryID string, chapterID string, progress float64, completed *bool, positionSeconds *float64, durationSeconds *float64) (*model.ReadingProgress, error) {
	entryID, err := parseID(libraryEntryID)
	if err != nil {
		return nil, err
	}
	chID, err := parseID(chapterID)
	if err != nil {
		return nil, err
	}
	comp := false
	if completed != nil {
		comp = *completed
	}
	prog, err := r.Sy.RecordProgress(ctx, entryID, chID, progress, comp, positionSeconds, durationSeconds)
	if err != nil {
		return nil, err
	}
	return toReadingProgress(prog), nil
}

// MarkChapterRead is the resolver for the markChapterRead field.
func (r *mutationResolver) MarkChapterRead(ctx context.Context, libraryEntryID string, chapterID string) (*model.ReadingProgress, error) {
	entryID, err := parseID(libraryEntryID)
	if err != nil {
		return nil, err
	}
	chID, err := parseID(chapterID)
	if err != nil {
		return nil, err
	}
	prog, err := r.Sy.MarkChapterRead(ctx, entryID, chID)
	if err != nil {
		return nil, err
	}
	return toReadingProgress(prog), nil
}

// Repositories is the resolver for the repositories field.
func (r *queryResolver) Repositories(ctx context.Context) ([]*model.Repository, error) {
	repos, err := r.Sy.ListRepositories(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Repository, 0, len(repos))
	for _, repo := range repos {
		out = append(out, toRepository(repo))
	}
	return out, nil
}

// AvailableExtensions is the resolver for the availableExtensions field.
func (r *queryResolver) AvailableExtensions(ctx context.Context, repositoryID string) ([]*model.Extension, error) {
	id, err := parseID(repositoryID)
	if err != nil {
		return nil, err
	}
	exts, err := r.Sy.ListAvailableExtensions(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Extension, 0, len(exts))
	for _, ext := range exts {
		out = append(out, toExtension(ext))
	}
	return out, nil
}

// InstalledExtensions is the resolver for the installedExtensions field.
func (r *queryResolver) InstalledExtensions(ctx context.Context) ([]*model.Extension, error) {
	exts, err := r.Sy.ListInstalledExtensions(ctx)
	if err != nil {
		return nil, err
	}
	out := make([]*model.Extension, 0, len(exts))
	for _, ext := range exts {
		out = append(out, toExtension(ext))
	}
	return out, nil
}

// Library is the resolver for the library field.
func (r *queryResolver) Library(ctx context.Context, contentType *model.ContentType) ([]*model.LibraryEntry, error) {
	entries, err := r.Sy.ListLibraryEntries(ctx, contentTypeToString(contentType))
	if err != nil {
		return nil, err
	}
	out := make([]*model.LibraryEntry, 0, len(entries))
	for _, e := range entries {
		out = append(out, toLibraryEntry(e))
	}
	return out, nil
}

// LibraryEntry is the resolver for the libraryEntry field.
func (r *queryResolver) LibraryEntry(ctx context.Context, id string) (*model.LibraryEntry, error) {
	entryID, err := parseID(id)
	if err != nil {
		return nil, err
	}
	entry, err := r.Sy.GetLibraryEntry(ctx, entryID)
	if err != nil {
		return nil, err
	}
	return toLibraryEntry(entry), nil
}

// ReadingProgress is the resolver for the readingProgress field.
func (r *queryResolver) ReadingProgress(ctx context.Context, libraryEntryID string) ([]*model.ReadingProgress, error) {
	id, err := parseID(libraryEntryID)
	if err != nil {
		return nil, err
	}
	list, err := r.Sy.ListReadingProgress(ctx, id)
	if err != nil {
		return nil, err
	}
	out := make([]*model.ReadingProgress, 0, len(list))
	for _, p := range list {
		out = append(out, toReadingProgress(p))
	}
	return out, nil
}

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, extensionID string, query string, page *int32) (*model.SearchResponse, error) {
	p := int32(1)
	if page != nil {
		p = *page
	}
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	resp, err := c.Search(ctx, extensionID, query, p)
	if err != nil {
		return nil, err
	}
	results := make([]*model.SearchResult, 0, len(resp.Results))
	for _, res := range resp.Results {
		var cover *string
		if res.CoverUrl != "" {
			cover = &res.CoverUrl
		}
		results = append(results, &model.SearchResult{
			SourceEntryID: res.SourceEntryId,
			Title:         res.Title,
			CoverURL:      cover,
		})
	}
	return &model.SearchResponse{
		Results:     results,
		HasNextPage: resp.HasNextPage,
	}, nil
}

// SourceDetails is the resolver for the sourceDetails field.
func (r *queryResolver) SourceDetails(ctx context.Context, extensionID string, sourceEntryID string) (*model.SourceDetails, error) {
	c, err := r.Sc.Ensure(ctx)
	if err != nil {
		return nil, err
	}
	d, err := c.GetDetails(ctx, extensionID, sourceEntryID)
	if err != nil {
		return nil, err
	}
	var desc, cover, status *string
	if d.Description != "" {
		desc = &d.Description
	}
	if d.CoverUrl != "" {
		cover = &d.CoverUrl
	}
	if d.Status != "" {
		status = &d.Status
	}
	return &model.SourceDetails{
		SourceEntryID: sourceEntryID,
		Title:         d.Title,
		Description:   desc,
		CoverURL:      cover,
		Status:        status,
	}, nil
}

// LibraryEntry returns LibraryEntryResolver implementation.
func (r *Resolver) LibraryEntry() LibraryEntryResolver { return &libraryEntryResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	libraryEntryResolver struct{ *Resolver }
	mutationResolver     struct{ *Resolver }
	queryResolver        struct{ *Resolver }
)
