// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chapters.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createChapter = `-- name: CreateChapter :one
INSERT INTO chapters (library_entry_id, external_id, title, number, uploaded_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(library_entry_id, external_id) DO UPDATE SET
    title = excluded.title,
    number = excluded.number,
    uploaded_at = excluded.uploaded_at
RETURNING id, library_entry_id, external_id, title, number, uploaded_at
`

type CreateChapterParams struct {
	LibraryEntryID int64           `json:"library_entry_id"`
	ExternalID     string          `json:"external_id"`
	Title          sql.NullString  `json:"title"`
	Number         sql.NullFloat64 `json:"number"`
	UploadedAt     sql.NullInt64   `json:"uploaded_at"`
}

func (q *Queries) CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, createChapter,
		arg.LibraryEntryID,
		arg.ExternalID,
		arg.Title,
		arg.Number,
		arg.UploadedAt,
	)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.LibraryEntryID,
		&i.ExternalID,
		&i.Title,
		&i.Number,
		&i.UploadedAt,
	)
	return i, err
}

const getAnimeEpisodeStream = `-- name: GetAnimeEpisodeStream :one
SELECT chapter_id, stream_url, local_path FROM anime_episode_streams WHERE chapter_id = ?
`

func (q *Queries) GetAnimeEpisodeStream(ctx context.Context, chapterID int64) (AnimeEpisodeStream, error) {
	row := q.db.QueryRowContext(ctx, getAnimeEpisodeStream, chapterID)
	var i AnimeEpisodeStream
	err := row.Scan(&i.ChapterID, &i.StreamUrl, &i.LocalPath)
	return i, err
}

const getChapter = `-- name: GetChapter :one
SELECT id, library_entry_id, external_id, title, number, uploaded_at FROM chapters WHERE id = ?
`

func (q *Queries) GetChapter(ctx context.Context, id int64) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapter, id)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.LibraryEntryID,
		&i.ExternalID,
		&i.Title,
		&i.Number,
		&i.UploadedAt,
	)
	return i, err
}

const getChapterByLibraryEntryAndExternalID = `-- name: GetChapterByLibraryEntryAndExternalID :one
SELECT id, library_entry_id, external_id, title, number, uploaded_at FROM chapters WHERE library_entry_id = ? AND external_id = ?
`

type GetChapterByLibraryEntryAndExternalIDParams struct {
	LibraryEntryID int64  `json:"library_entry_id"`
	ExternalID     string `json:"external_id"`
}

func (q *Queries) GetChapterByLibraryEntryAndExternalID(ctx context.Context, arg GetChapterByLibraryEntryAndExternalIDParams) (Chapter, error) {
	row := q.db.QueryRowContext(ctx, getChapterByLibraryEntryAndExternalID, arg.LibraryEntryID, arg.ExternalID)
	var i Chapter
	err := row.Scan(
		&i.ID,
		&i.LibraryEntryID,
		&i.ExternalID,
		&i.Title,
		&i.Number,
		&i.UploadedAt,
	)
	return i, err
}

const getChapterDownloadContext = `-- name: GetChapterDownloadContext :one
SELECT
    c.id AS chapter_id,
    c.external_id AS source_chapter_id,
    c.title AS chapter_title,
    c.number AS chapter_number,
    le.external_id AS source_entry_id,
    le.title AS library_title,
    le.content_type AS content_type,
    e.package_name AS extension_package_name
FROM chapters c
JOIN library_entries le ON le.id = c.library_entry_id
JOIN extensions e ON e.id = le.extension_id
WHERE c.id = ?
`

type GetChapterDownloadContextRow struct {
	ChapterID            int64           `json:"chapter_id"`
	SourceChapterID      string          `json:"source_chapter_id"`
	ChapterTitle         sql.NullString  `json:"chapter_title"`
	ChapterNumber        sql.NullFloat64 `json:"chapter_number"`
	SourceEntryID        string          `json:"source_entry_id"`
	LibraryTitle         string          `json:"library_title"`
	ContentType          string          `json:"content_type"`
	ExtensionPackageName string          `json:"extension_package_name"`
}

func (q *Queries) GetChapterDownloadContext(ctx context.Context, id int64) (GetChapterDownloadContextRow, error) {
	row := q.db.QueryRowContext(ctx, getChapterDownloadContext, id)
	var i GetChapterDownloadContextRow
	err := row.Scan(
		&i.ChapterID,
		&i.SourceChapterID,
		&i.ChapterTitle,
		&i.ChapterNumber,
		&i.SourceEntryID,
		&i.LibraryTitle,
		&i.ContentType,
		&i.ExtensionPackageName,
	)
	return i, err
}

const getNovelChapterContent = `-- name: GetNovelChapterContent :one
SELECT chapter_id, local_path FROM novel_chapter_content WHERE chapter_id = ?
`

func (q *Queries) GetNovelChapterContent(ctx context.Context, chapterID int64) (NovelChapterContent, error) {
	row := q.db.QueryRowContext(ctx, getNovelChapterContent, chapterID)
	var i NovelChapterContent
	err := row.Scan(&i.ChapterID, &i.LocalPath)
	return i, err
}

const listChaptersByLibraryEntry = `-- name: ListChaptersByLibraryEntry :many
SELECT id, library_entry_id, external_id, title, number, uploaded_at FROM chapters WHERE library_entry_id = ? ORDER BY number
`

func (q *Queries) ListChaptersByLibraryEntry(ctx context.Context, libraryEntryID int64) ([]Chapter, error) {
	rows, err := q.db.QueryContext(ctx, listChaptersByLibraryEntry, libraryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Chapter{}
	for rows.Next() {
		var i Chapter
		if err := rows.Scan(
			&i.ID,
			&i.LibraryEntryID,
			&i.ExternalID,
			&i.Title,
			&i.Number,
			&i.UploadedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMangaPages = `-- name: ListMangaPages :many
SELECT chapter_id, page_number, local_path FROM manga_pages WHERE chapter_id = ? ORDER BY page_number
`

func (q *Queries) ListMangaPages(ctx context.Context, chapterID int64) ([]MangaPage, error) {
	rows, err := q.db.QueryContext(ctx, listMangaPages, chapterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MangaPage{}
	for rows.Next() {
		var i MangaPage
		if err := rows.Scan(&i.ChapterID, &i.PageNumber, &i.LocalPath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAnimeEpisodeStream = `-- name: UpsertAnimeEpisodeStream :exec
INSERT INTO anime_episode_streams (chapter_id, stream_url, local_path)
VALUES (?, ?, ?)
ON CONFLICT(chapter_id) DO UPDATE SET
    stream_url = excluded.stream_url,
    local_path = excluded.local_path
`

type UpsertAnimeEpisodeStreamParams struct {
	ChapterID int64          `json:"chapter_id"`
	StreamUrl sql.NullString `json:"stream_url"`
	LocalPath sql.NullString `json:"local_path"`
}

func (q *Queries) UpsertAnimeEpisodeStream(ctx context.Context, arg UpsertAnimeEpisodeStreamParams) error {
	_, err := q.db.ExecContext(ctx, upsertAnimeEpisodeStream, arg.ChapterID, arg.StreamUrl, arg.LocalPath)
	return err
}

const upsertMangaPage = `-- name: UpsertMangaPage :exec
INSERT INTO manga_pages (chapter_id, page_number, local_path)
VALUES (?, ?, ?)
ON CONFLICT(chapter_id, page_number) DO UPDATE SET local_path = excluded.local_path
`

type UpsertMangaPageParams struct {
	ChapterID  int64          `json:"chapter_id"`
	PageNumber int64          `json:"page_number"`
	LocalPath  sql.NullString `json:"local_path"`
}

func (q *Queries) UpsertMangaPage(ctx context.Context, arg UpsertMangaPageParams) error {
	_, err := q.db.ExecContext(ctx, upsertMangaPage, arg.ChapterID, arg.PageNumber, arg.LocalPath)
	return err
}

const upsertNovelChapterContent = `-- name: UpsertNovelChapterContent :exec
INSERT INTO novel_chapter_content (chapter_id, local_path)
VALUES (?, ?)
ON CONFLICT(chapter_id) DO UPDATE SET local_path = excluded.local_path
`

type UpsertNovelChapterContentParams struct {
	ChapterID int64          `json:"chapter_id"`
	LocalPath sql.NullString `json:"local_path"`
}

func (q *Queries) UpsertNovelChapterContent(ctx context.Context, arg UpsertNovelChapterContentParams) error {
	_, err := q.db.ExecContext(ctx, upsertNovelChapterContent, arg.ChapterID, arg.LocalPath)
	return err
}
