// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: content_filter.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createContentFilterRule = `-- name: CreateContentFilterRule :one
INSERT INTO content_filter_rules (category, field, keyword, min_weight, block_level, is_default)
VALUES (?, ?, ?, ?, ?, 0)
ON CONFLICT(field, keyword, category) DO UPDATE SET
    min_weight = excluded.min_weight,
    block_level = excluded.block_level
RETURNING id, category, field, keyword, min_weight, block_level, is_default, created_at
`

type CreateContentFilterRuleParams struct {
	Category   string `json:"category"`
	Field      string `json:"field"`
	Keyword    string `json:"keyword"`
	MinWeight  int64  `json:"min_weight"`
	BlockLevel int64  `json:"block_level"`
}

func (q *Queries) CreateContentFilterRule(ctx context.Context, arg CreateContentFilterRuleParams) (ContentFilterRule, error) {
	row := q.db.QueryRowContext(ctx, createContentFilterRule,
		arg.Category,
		arg.Field,
		arg.Keyword,
		arg.MinWeight,
		arg.BlockLevel,
	)
	var i ContentFilterRule
	err := row.Scan(
		&i.ID,
		&i.Category,
		&i.Field,
		&i.Keyword,
		&i.MinWeight,
		&i.BlockLevel,
		&i.IsDefault,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContentFilterRule = `-- name: DeleteContentFilterRule :exec
DELETE FROM content_filter_rules WHERE id = ?
`

func (q *Queries) DeleteContentFilterRule(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteContentFilterRule, id)
	return err
}

const deleteUserContentFilterRules = `-- name: DeleteUserContentFilterRules :exec
DELETE FROM content_filter_rules WHERE is_default = 0
`

func (q *Queries) DeleteUserContentFilterRules(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteUserContentFilterRules)
	return err
}

const getContentFilterInputs = `-- name: GetContentFilterInputs :one
SELECT title, description FROM media WHERE id = ?
`

type GetContentFilterInputsRow struct {
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) GetContentFilterInputs(ctx context.Context, id int64) (GetContentFilterInputsRow, error) {
	row := q.db.QueryRowContext(ctx, getContentFilterInputs, id)
	var i GetContentFilterInputsRow
	err := row.Scan(&i.Title, &i.Description)
	return i, err
}

const libraryGenreFacets = `-- name: LibraryGenreFacets :many
SELECT g.name AS name,
       CAST(COUNT(*) AS INTEGER) AS count,
       CAST(0 AS INTEGER) AS max_weight
FROM media_genres mg
JOIN genres g ON g.id = mg.genre_id
JOIN media m ON m.id = mg.media_id
WHERE m.added_at IS NOT NULL
GROUP BY g.id
HAVING COUNT(*) >= ?1
ORDER BY count DESC, name
`

type LibraryGenreFacetsRow struct {
	Name      string `json:"name"`
	Count     int64  `json:"count"`
	MaxWeight int64  `json:"max_weight"`
}

func (q *Queries) LibraryGenreFacets(ctx context.Context, minCount interface{}) ([]LibraryGenreFacetsRow, error) {
	rows, err := q.db.QueryContext(ctx, libraryGenreFacets, minCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryGenreFacetsRow{}
	for rows.Next() {
		var i LibraryGenreFacetsRow
		if err := rows.Scan(&i.Name, &i.Count, &i.MaxWeight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const libraryTagFacets = `-- name: LibraryTagFacets :many
SELECT t.name AS name,
       CAST(COUNT(*) AS INTEGER) AS count,
       CAST(COALESCE(MAX(mt.weight), 0) AS INTEGER) AS max_weight
FROM media_tags mt
JOIN tags t ON t.id = mt.tag_id
JOIN media m ON m.id = mt.media_id
WHERE m.added_at IS NOT NULL
GROUP BY t.id
HAVING COUNT(*) >= ?1
ORDER BY count DESC, name
`

type LibraryTagFacetsRow struct {
	Name      string `json:"name"`
	Count     int64  `json:"count"`
	MaxWeight int64  `json:"max_weight"`
}

func (q *Queries) LibraryTagFacets(ctx context.Context, minCount interface{}) ([]LibraryTagFacetsRow, error) {
	rows, err := q.db.QueryContext(ctx, libraryTagFacets, minCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryTagFacetsRow{}
	for rows.Next() {
		var i LibraryTagFacetsRow
		if err := rows.Scan(&i.Name, &i.Count, &i.MaxWeight); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContentFilterRules = `-- name: ListContentFilterRules :many
SELECT id, category, field, keyword, min_weight, block_level, is_default, created_at FROM content_filter_rules ORDER BY category, field, keyword
`

func (q *Queries) ListContentFilterRules(ctx context.Context) ([]ContentFilterRule, error) {
	rows, err := q.db.QueryContext(ctx, listContentFilterRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentFilterRule{}
	for rows.Next() {
		var i ContentFilterRule
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Field,
			&i.Keyword,
			&i.MinWeight,
			&i.BlockLevel,
			&i.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaIDsWithSparseTags = `-- name: ListMediaIDsWithSparseTags :many
SELECT m.id
FROM media m
JOIN metadata_links ml ON ml.media_id = m.id AND ml.provider = 'anilist'
WHERE m.added_at IS NOT NULL
  AND (SELECT COUNT(*) FROM media_tags mt WHERE mt.media_id = m.id) < ?
`

func (q *Queries) ListMediaIDsWithSparseTags(ctx context.Context, mediaID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listMediaIDsWithSparseTags, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecomputableMediaIDs = `-- name: ListRecomputableMediaIDs :many
SELECT id FROM media WHERE added_at IS NOT NULL ORDER BY id
`

func (q *Queries) ListRecomputableMediaIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listRecomputableMediaIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMediaContentBlockRank = `-- name: SetMediaContentBlockRank :exec
UPDATE media SET content_block_rank = ? WHERE id = ?
`

type SetMediaContentBlockRankParams struct {
	ContentBlockRank sql.NullInt64 `json:"content_block_rank"`
	ID               int64         `json:"id"`
}

func (q *Queries) SetMediaContentBlockRank(ctx context.Context, arg SetMediaContentBlockRankParams) error {
	_, err := q.db.ExecContext(ctx, setMediaContentBlockRank, arg.ContentBlockRank, arg.ID)
	return err
}
