// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: downloads.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
	"time"
)

const clearDownloads = `-- name: ClearDownloads :exec
DELETE FROM downloads WHERE status IN ('queued', 'failed')
`

func (q *Queries) ClearDownloads(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearDownloads)
	return err
}

const clearDownloadsByStatus = `-- name: ClearDownloadsByStatus :exec
DELETE FROM downloads WHERE status IN (/*SLICE:statuses*/?)
`

func (q *Queries) ClearDownloadsByStatus(ctx context.Context, statuses []string) error {
	query := clearDownloadsByStatus
	var queryParams []interface{}
	if len(statuses) > 0 {
		for _, v := range statuses {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:statuses*/?", strings.Repeat(",?", len(statuses))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:statuses*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const completeDownload = `-- name: CompleteDownload :exec
UPDATE downloads SET status = 'done', progress = 1, completed_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) CompleteDownload(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, completeDownload, id)
	return err
}

const countDownloadedChaptersByMediaIDs = `-- name: CountDownloadedChaptersByMediaIDs :many

SELECT c.media_id AS media_id, COUNT(*) AS download_count
FROM downloads d
JOIN chapters c ON c.id = d.chapter_id
WHERE c.media_id IN (/*SLICE:media_ids*/?)
  AND d.status = 'done'
GROUP BY c.media_id
`

type CountDownloadedChaptersByMediaIDsRow struct {
	MediaID       int64 `json:"media_id"`
	DownloadCount int64 `json:"download_count"`
}

func (q *Queries) CountDownloadedChaptersByMediaIDs(ctx context.Context, mediaIds []int64) ([]CountDownloadedChaptersByMediaIDsRow, error) {
	query := countDownloadedChaptersByMediaIDs
	var queryParams []interface{}
	if len(mediaIds) > 0 {
		for _, v := range mediaIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:media_ids*/?", strings.Repeat(",?", len(mediaIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:media_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDownloadedChaptersByMediaIDsRow{}
	for rows.Next() {
		var i CountDownloadedChaptersByMediaIDsRow
		if err := rows.Scan(&i.MediaID, &i.DownloadCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countDownloadsByStatus = `-- name: CountDownloadsByStatus :many

SELECT status, COUNT(*) AS count FROM downloads GROUP BY status
`

type CountDownloadsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountDownloadsByStatus(ctx context.Context) ([]CountDownloadsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countDownloadsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountDownloadsByStatusRow{}
	for rows.Next() {
		var i CountDownloadsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteDownload = `-- name: DeleteDownload :exec
DELETE FROM downloads WHERE id = ?
`

func (q *Queries) DeleteDownload(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteDownload, id)
	return err
}

const deleteDownloadByChapter = `-- name: DeleteDownloadByChapter :exec
DELETE FROM downloads WHERE chapter_id = ?
`

func (q *Queries) DeleteDownloadByChapter(ctx context.Context, chapterID int64) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadByChapter, chapterID)
	return err
}

const deleteDownloadsByChapters = `-- name: DeleteDownloadsByChapters :exec
DELETE FROM downloads WHERE chapter_id IN (/*SLICE:chapter_ids*/?)
`

func (q *Queries) DeleteDownloadsByChapters(ctx context.Context, chapterIds []int64) error {
	query := deleteDownloadsByChapters
	var queryParams []interface{}
	if len(chapterIds) > 0 {
		for _, v := range chapterIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:chapter_ids*/?", strings.Repeat(",?", len(chapterIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:chapter_ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const enqueueDownload = `-- name: EnqueueDownload :one
INSERT INTO downloads (chapter_id, status, position)
VALUES (?, 'queued', COALESCE((SELECT MAX(position) FROM downloads WHERE status = 'queued'), 0) + 1)
RETURNING id, chapter_id, status, progress, downloaded_bytes, bytes_per_sec, position, error, created_at, completed_at
`

func (q *Queries) EnqueueDownload(ctx context.Context, chapterID int64) (Download, error) {
	row := q.db.QueryRowContext(ctx, enqueueDownload, chapterID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Status,
		&i.Progress,
		&i.DownloadedBytes,
		&i.BytesPerSec,
		&i.Position,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failDownload = `-- name: FailDownload :exec
UPDATE downloads SET status = 'failed', error = ? WHERE id = ?
`

type FailDownloadParams struct {
	Error sql.NullString `json:"error"`
	ID    int64          `json:"id"`
}

func (q *Queries) FailDownload(ctx context.Context, arg FailDownloadParams) error {
	_, err := q.db.ExecContext(ctx, failDownload, arg.Error, arg.ID)
	return err
}

const getLatestDownloadForChapter = `-- name: GetLatestDownloadForChapter :one
SELECT id, chapter_id, status, progress, downloaded_bytes, bytes_per_sec, position, error, created_at, completed_at FROM downloads WHERE chapter_id = ? ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestDownloadForChapter(ctx context.Context, chapterID int64) (Download, error) {
	row := q.db.QueryRowContext(ctx, getLatestDownloadForChapter, chapterID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Status,
		&i.Progress,
		&i.DownloadedBytes,
		&i.BytesPerSec,
		&i.Position,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLatestDownloadsByChapterIDs = `-- name: GetLatestDownloadsByChapterIDs :many

SELECT d.id, d.chapter_id, d.status, d.progress, d.downloaded_bytes, d.bytes_per_sec, d.position, d.error, d.created_at, d.completed_at FROM downloads d
WHERE d.chapter_id IN (/*SLICE:chapter_ids*/?)
  AND d.id = (
    SELECT d2.id FROM downloads d2
    WHERE d2.chapter_id = d.chapter_id
    ORDER BY d2.created_at DESC LIMIT 1
  )
`

func (q *Queries) GetLatestDownloadsByChapterIDs(ctx context.Context, chapterIds []int64) ([]Download, error) {
	query := getLatestDownloadsByChapterIDs
	var queryParams []interface{}
	if len(chapterIds) > 0 {
		for _, v := range chapterIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:chapter_ids*/?", strings.Repeat(",?", len(chapterIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:chapter_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Status,
			&i.Progress,
			&i.DownloadedBytes,
			&i.BytesPerSec,
			&i.Position,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getQueuedDownloadByChapter = `-- name: GetQueuedDownloadByChapter :one
SELECT id, chapter_id, status, progress, downloaded_bytes, bytes_per_sec, position, error, created_at, completed_at FROM downloads WHERE chapter_id = ? AND status = 'queued'
`

func (q *Queries) GetQueuedDownloadByChapter(ctx context.Context, chapterID int64) (Download, error) {
	row := q.db.QueryRowContext(ctx, getQueuedDownloadByChapter, chapterID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Status,
		&i.Progress,
		&i.DownloadedBytes,
		&i.BytesPerSec,
		&i.Position,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listAllDownloads = `-- name: ListAllDownloads :many
SELECT d.id, d.chapter_id, d.status, d.progress, d.downloaded_bytes, d.bytes_per_sec, d.position, d.error, d.created_at, d.completed_at, c.media_id AS media_id FROM downloads d JOIN chapters c ON c.id = d.chapter_id ORDER BY
  CASE d.status WHEN 'downloading' THEN 0 WHEN 'queued' THEN 1 ELSE 2 END,
  d.position,
  d.created_at DESC
`

type ListAllDownloadsRow struct {
	ID              int64           `json:"id"`
	ChapterID       int64           `json:"chapter_id"`
	Status          string          `json:"status"`
	Progress        float64         `json:"progress"`
	DownloadedBytes sql.NullInt64   `json:"downloaded_bytes"`
	BytesPerSec     sql.NullFloat64 `json:"bytes_per_sec"`
	Position        sql.NullInt64   `json:"position"`
	Error           sql.NullString  `json:"error"`
	CreatedAt       time.Time       `json:"created_at"`
	CompletedAt     sql.NullTime    `json:"completed_at"`
	MediaID         int64           `json:"media_id"`
}

func (q *Queries) ListAllDownloads(ctx context.Context) ([]ListAllDownloadsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllDownloadsRow{}
	for rows.Next() {
		var i ListAllDownloadsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Status,
			&i.Progress,
			&i.DownloadedBytes,
			&i.BytesPerSec,
			&i.Position,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
			&i.MediaID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listQueuedDownloads = `-- name: ListQueuedDownloads :many
SELECT id, chapter_id, status, progress, downloaded_bytes, bytes_per_sec, position, error, created_at, completed_at FROM downloads WHERE status = 'queued' ORDER BY position
`

func (q *Queries) ListQueuedDownloads(ctx context.Context) ([]Download, error) {
	rows, err := q.db.QueryContext(ctx, listQueuedDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Download{}
	for rows.Next() {
		var i Download
		if err := rows.Scan(
			&i.ID,
			&i.ChapterID,
			&i.Status,
			&i.Progress,
			&i.DownloadedBytes,
			&i.BytesPerSec,
			&i.Position,
			&i.Error,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const requeueOrphanedDownloads = `-- name: RequeueOrphanedDownloads :exec
UPDATE downloads SET status = 'queued', progress = 0 WHERE status = 'downloading'
`

func (q *Queries) RequeueOrphanedDownloads(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, requeueOrphanedDownloads)
	return err
}

const retryDownload = `-- name: RetryDownload :one
UPDATE downloads SET status = 'queued', progress = 0, error = NULL, downloaded_bytes = NULL, bytes_per_sec = NULL
WHERE id = ? AND status = 'failed'
RETURNING id, chapter_id, status, progress, downloaded_bytes, bytes_per_sec, position, error, created_at, completed_at
`

func (q *Queries) RetryDownload(ctx context.Context, id int64) (Download, error) {
	row := q.db.QueryRowContext(ctx, retryDownload, id)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.ChapterID,
		&i.Status,
		&i.Progress,
		&i.DownloadedBytes,
		&i.BytesPerSec,
		&i.Position,
		&i.Error,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const setDownloadPosition = `-- name: SetDownloadPosition :exec
UPDATE downloads SET position = ? WHERE id = ?
`

type SetDownloadPositionParams struct {
	Position sql.NullInt64 `json:"position"`
	ID       int64         `json:"id"`
}

func (q *Queries) SetDownloadPosition(ctx context.Context, arg SetDownloadPositionParams) error {
	_, err := q.db.ExecContext(ctx, setDownloadPosition, arg.Position, arg.ID)
	return err
}

const updateDownloadProgress = `-- name: UpdateDownloadProgress :exec
UPDATE downloads SET status = ?, progress = ? WHERE id = ?
`

type UpdateDownloadProgressParams struct {
	Status   string  `json:"status"`
	Progress float64 `json:"progress"`
	ID       int64   `json:"id"`
}

func (q *Queries) UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadProgress, arg.Status, arg.Progress, arg.ID)
	return err
}

const updateDownloadStats = `-- name: UpdateDownloadStats :exec
UPDATE downloads SET status = ?, progress = ?, downloaded_bytes = ?, bytes_per_sec = ? WHERE id = ?
`

type UpdateDownloadStatsParams struct {
	Status          string          `json:"status"`
	Progress        float64         `json:"progress"`
	DownloadedBytes sql.NullInt64   `json:"downloaded_bytes"`
	BytesPerSec     sql.NullFloat64 `json:"bytes_per_sec"`
	ID              int64           `json:"id"`
}

func (q *Queries) UpdateDownloadStats(ctx context.Context, arg UpdateDownloadStatsParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadStats,
		arg.Status,
		arg.Progress,
		arg.DownloadedBytes,
		arg.BytesPerSec,
		arg.ID,
	)
	return err
}
