// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folders.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const addEntryToFolder = `-- name: AddEntryToFolder :exec
INSERT INTO library_entry_folders (library_entry_id, folder_id) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddEntryToFolderParams struct {
	LibraryEntryID int64 `json:"library_entry_id"`
	FolderID       int64 `json:"folder_id"`
}

func (q *Queries) AddEntryToFolder(ctx context.Context, arg AddEntryToFolderParams) error {
	_, err := q.db.ExecContext(ctx, addEntryToFolder, arg.LibraryEntryID, arg.FolderID)
	return err
}

const createFolder = `-- name: CreateFolder :one
INSERT INTO folders (name, kind, parent_folder_id) VALUES (?, 'custom', ?)
RETURNING id, name, kind, system_key, parent_folder_id, sort_order, created_at
`

type CreateFolderParams struct {
	Name           string        `json:"name"`
	ParentFolderID sql.NullInt64 `json:"parent_folder_id"`
}

func (q *Queries) CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, createFolder, arg.Name, arg.ParentFolderID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SystemKey,
		&i.ParentFolderID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFolder = `-- name: DeleteFolder :exec
DELETE FROM folders WHERE id = ? AND kind = 'custom'
`

func (q *Queries) DeleteFolder(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFolder, id)
	return err
}

const getFolder = `-- name: GetFolder :one
SELECT id, name, kind, system_key, parent_folder_id, sort_order, created_at FROM folders WHERE id = ?
`

func (q *Queries) GetFolder(ctx context.Context, id int64) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolder, id)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SystemKey,
		&i.ParentFolderID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getFolderBySystemKey = `-- name: GetFolderBySystemKey :one
SELECT id, name, kind, system_key, parent_folder_id, sort_order, created_at FROM folders WHERE system_key = ?
`

func (q *Queries) GetFolderBySystemKey(ctx context.Context, systemKey sql.NullString) (Folder, error) {
	row := q.db.QueryRowContext(ctx, getFolderBySystemKey, systemKey)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SystemKey,
		&i.ParentFolderID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const listChildFolders = `-- name: ListChildFolders :many
SELECT id, name, kind, system_key, parent_folder_id, sort_order, created_at FROM folders WHERE parent_folder_id = ? ORDER BY sort_order, name
`

func (q *Queries) ListChildFolders(ctx context.Context, parentFolderID sql.NullInt64) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listChildFolders, parentFolderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.SystemKey,
			&i.ParentFolderID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntriesInFolder = `-- name: ListEntriesInFolder :many
SELECT le.id, le.extension_id, le.extension_name, le.external_id, le.content_type, le.title, le.cover_path, le.description, le.status, le.extension_removed_at, le.added_at FROM library_entries le
JOIN library_entry_folders lef ON lef.library_entry_id = le.id
WHERE lef.folder_id = ?
ORDER BY le.added_at DESC
`

func (q *Queries) ListEntriesInFolder(ctx context.Context, folderID int64) ([]LibraryEntry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesInFolder, folderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryEntry{}
	for rows.Next() {
		var i LibraryEntry
		if err := rows.Scan(
			&i.ID,
			&i.ExtensionID,
			&i.ExtensionName,
			&i.ExternalID,
			&i.ContentType,
			&i.Title,
			&i.CoverPath,
			&i.Description,
			&i.Status,
			&i.ExtensionRemovedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFolders = `-- name: ListFolders :many
SELECT id, name, kind, system_key, parent_folder_id, sort_order, created_at FROM folders ORDER BY kind, sort_order, name
`

func (q *Queries) ListFolders(ctx context.Context) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFolders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.SystemKey,
			&i.ParentFolderID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFoldersForEntry = `-- name: ListFoldersForEntry :many
SELECT f.id, f.name, f.kind, f.system_key, f.parent_folder_id, f.sort_order, f.created_at FROM folders f
JOIN library_entry_folders lef ON lef.folder_id = f.id
WHERE lef.library_entry_id = ?
ORDER BY f.kind, f.sort_order, f.name
`

func (q *Queries) ListFoldersForEntry(ctx context.Context, libraryEntryID int64) ([]Folder, error) {
	rows, err := q.db.QueryContext(ctx, listFoldersForEntry, libraryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Folder{}
	for rows.Next() {
		var i Folder
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.SystemKey,
			&i.ParentFolderID,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeEntryFromFolder = `-- name: RemoveEntryFromFolder :exec
DELETE FROM library_entry_folders WHERE library_entry_id = ? AND folder_id = ?
`

type RemoveEntryFromFolderParams struct {
	LibraryEntryID int64 `json:"library_entry_id"`
	FolderID       int64 `json:"folder_id"`
}

func (q *Queries) RemoveEntryFromFolder(ctx context.Context, arg RemoveEntryFromFolderParams) error {
	_, err := q.db.ExecContext(ctx, removeEntryFromFolder, arg.LibraryEntryID, arg.FolderID)
	return err
}

const removeEntryFromFoldersByKind = `-- name: RemoveEntryFromFoldersByKind :exec
DELETE FROM library_entry_folders
WHERE library_entry_id = ?
AND folder_id IN (SELECT id FROM folders WHERE kind = ?)
`

type RemoveEntryFromFoldersByKindParams struct {
	LibraryEntryID int64  `json:"library_entry_id"`
	Kind           string `json:"kind"`
}

func (q *Queries) RemoveEntryFromFoldersByKind(ctx context.Context, arg RemoveEntryFromFoldersByKindParams) error {
	_, err := q.db.ExecContext(ctx, removeEntryFromFoldersByKind, arg.LibraryEntryID, arg.Kind)
	return err
}

const renameFolder = `-- name: RenameFolder :one
UPDATE folders SET name = ? WHERE id = ? AND kind = 'custom'
RETURNING id, name, kind, system_key, parent_folder_id, sort_order, created_at
`

type RenameFolderParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error) {
	row := q.db.QueryRowContext(ctx, renameFolder, arg.Name, arg.ID)
	var i Folder
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.SystemKey,
		&i.ParentFolderID,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}
