// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: library.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createLibraryEntry = `-- name: CreateLibraryEntry :one
INSERT INTO library_entries (
    extension_id, extension_name, external_id, content_type, title, cover_path, description, status
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(extension_id, external_id) DO UPDATE SET
    title = excluded.title,
    cover_path = excluded.cover_path,
    description = excluded.description,
    status = excluded.status
RETURNING id, extension_id, extension_name, external_id, content_type, title, cover_path, description, status, extension_removed_at, added_at
`

type CreateLibraryEntryParams struct {
	ExtensionID   sql.NullInt64  `json:"extension_id"`
	ExtensionName string         `json:"extension_name"`
	ExternalID    string         `json:"external_id"`
	ContentType   string         `json:"content_type"`
	Title         string         `json:"title"`
	CoverPath     sql.NullString `json:"cover_path"`
	Description   sql.NullString `json:"description"`
	Status        sql.NullString `json:"status"`
}

func (q *Queries) CreateLibraryEntry(ctx context.Context, arg CreateLibraryEntryParams) (LibraryEntry, error) {
	row := q.db.QueryRowContext(ctx, createLibraryEntry,
		arg.ExtensionID,
		arg.ExtensionName,
		arg.ExternalID,
		arg.ContentType,
		arg.Title,
		arg.CoverPath,
		arg.Description,
		arg.Status,
	)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.ExtensionID,
		&i.ExtensionName,
		&i.ExternalID,
		&i.ContentType,
		&i.Title,
		&i.CoverPath,
		&i.Description,
		&i.Status,
		&i.ExtensionRemovedAt,
		&i.AddedAt,
	)
	return i, err
}

const deleteLibraryEntry = `-- name: DeleteLibraryEntry :exec
DELETE FROM library_entries WHERE id = ?
`

func (q *Queries) DeleteLibraryEntry(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLibraryEntry, id)
	return err
}

const getLibraryEntry = `-- name: GetLibraryEntry :one
SELECT id, extension_id, extension_name, external_id, content_type, title, cover_path, description, status, extension_removed_at, added_at FROM library_entries WHERE id = ?
`

func (q *Queries) GetLibraryEntry(ctx context.Context, id int64) (LibraryEntry, error) {
	row := q.db.QueryRowContext(ctx, getLibraryEntry, id)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.ExtensionID,
		&i.ExtensionName,
		&i.ExternalID,
		&i.ContentType,
		&i.Title,
		&i.CoverPath,
		&i.Description,
		&i.Status,
		&i.ExtensionRemovedAt,
		&i.AddedAt,
	)
	return i, err
}

const getLibraryEntryByExtensionAndExternalID = `-- name: GetLibraryEntryByExtensionAndExternalID :one
SELECT le.id, le.extension_id, le.extension_name, le.external_id, le.content_type, le.title, le.cover_path, le.description, le.status, le.extension_removed_at, le.added_at FROM library_entries le
JOIN extensions e ON e.id = le.extension_id
WHERE e.package_name = ? AND le.external_id = ?
`

type GetLibraryEntryByExtensionAndExternalIDParams struct {
	PackageName string `json:"package_name"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) GetLibraryEntryByExtensionAndExternalID(ctx context.Context, arg GetLibraryEntryByExtensionAndExternalIDParams) (LibraryEntry, error) {
	row := q.db.QueryRowContext(ctx, getLibraryEntryByExtensionAndExternalID, arg.PackageName, arg.ExternalID)
	var i LibraryEntry
	err := row.Scan(
		&i.ID,
		&i.ExtensionID,
		&i.ExtensionName,
		&i.ExternalID,
		&i.ContentType,
		&i.Title,
		&i.CoverPath,
		&i.Description,
		&i.Status,
		&i.ExtensionRemovedAt,
		&i.AddedAt,
	)
	return i, err
}

const listLibraryEntries = `-- name: ListLibraryEntries :many
SELECT id, extension_id, extension_name, external_id, content_type, title, cover_path, description, status, extension_removed_at, added_at FROM library_entries ORDER BY added_at DESC
`

func (q *Queries) ListLibraryEntries(ctx context.Context) ([]LibraryEntry, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryEntry{}
	for rows.Next() {
		var i LibraryEntry
		if err := rows.Scan(
			&i.ID,
			&i.ExtensionID,
			&i.ExtensionName,
			&i.ExternalID,
			&i.ContentType,
			&i.Title,
			&i.CoverPath,
			&i.Description,
			&i.Status,
			&i.ExtensionRemovedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLibraryEntriesByContentType = `-- name: ListLibraryEntriesByContentType :many
SELECT id, extension_id, extension_name, external_id, content_type, title, cover_path, description, status, extension_removed_at, added_at FROM library_entries WHERE content_type = ? ORDER BY added_at DESC
`

func (q *Queries) ListLibraryEntriesByContentType(ctx context.Context, contentType string) ([]LibraryEntry, error) {
	rows, err := q.db.QueryContext(ctx, listLibraryEntriesByContentType, contentType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryEntry{}
	for rows.Next() {
		var i LibraryEntry
		if err := rows.Scan(
			&i.ID,
			&i.ExtensionID,
			&i.ExtensionName,
			&i.ExternalID,
			&i.ContentType,
			&i.Title,
			&i.CoverPath,
			&i.Description,
			&i.Status,
			&i.ExtensionRemovedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markLibraryEntriesExtensionRemoved = `-- name: MarkLibraryEntriesExtensionRemoved :exec
UPDATE library_entries
SET extension_removed_at = CURRENT_TIMESTAMP
WHERE extension_id = ? AND extension_removed_at IS NULL
`

func (q *Queries) MarkLibraryEntriesExtensionRemoved(ctx context.Context, extensionID sql.NullInt64) error {
	_, err := q.db.ExecContext(ctx, markLibraryEntriesExtensionRemoved, extensionID)
	return err
}
