// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type AnimeEpisodeStream struct {
	ChapterID int64          `json:"chapter_id"`
	StreamUrl sql.NullString `json:"stream_url"`
	LocalPath sql.NullString `json:"local_path"`
}

type Chapter struct {
	ID             int64           `json:"id"`
	LibraryEntryID int64           `json:"library_entry_id"`
	ExternalID     string          `json:"external_id"`
	Title          sql.NullString  `json:"title"`
	Number         sql.NullFloat64 `json:"number"`
	UploadedAt     sql.NullTime    `json:"uploaded_at"`
}

type Download struct {
	ID          int64          `json:"id"`
	ChapterID   int64          `json:"chapter_id"`
	Status      string         `json:"status"`
	Progress    float64        `json:"progress"`
	Error       sql.NullString `json:"error"`
	CreatedAt   time.Time      `json:"created_at"`
	CompletedAt sql.NullTime   `json:"completed_at"`
}

type Extension struct {
	ID               int64          `json:"id"`
	RepositoryID     int64          `json:"repository_id"`
	PackageName      string         `json:"package_name"`
	Name             string         `json:"name"`
	Version          string         `json:"version"`
	ContentType      string         `json:"content_type"`
	Lang             string         `json:"lang"`
	IconUrl          sql.NullString `json:"icon_url"`
	ApkUrl           string         `json:"apk_url"`
	JarUrl           sql.NullString `json:"jar_url"`
	JarPath          sql.NullString `json:"jar_path"`
	Installed        bool           `json:"installed"`
	Enabled          bool           `json:"enabled"`
	DiscoveredAt     time.Time      `json:"discovered_at"`
	InstalledAt      sql.NullTime   `json:"installed_at"`
	InstalledVersion sql.NullString `json:"installed_version"`
	NeedsUpdate      sql.NullBool   `json:"needs_update"`
}

type LibraryEntry struct {
	ID          int64          `json:"id"`
	ExtensionID int64          `json:"extension_id"`
	ExternalID  string         `json:"external_id"`
	ContentType string         `json:"content_type"`
	Title       string         `json:"title"`
	CoverPath   sql.NullString `json:"cover_path"`
	Description sql.NullString `json:"description"`
	Status      sql.NullString `json:"status"`
	AddedAt     time.Time      `json:"added_at"`
}

type MangaPage struct {
	ChapterID  int64          `json:"chapter_id"`
	PageNumber int64          `json:"page_number"`
	LocalPath  sql.NullString `json:"local_path"`
}

type NovelChapterContent struct {
	ChapterID int64          `json:"chapter_id"`
	LocalPath sql.NullString `json:"local_path"`
}

type ReadingProgress struct {
	ID             int64     `json:"id"`
	LibraryEntryID int64     `json:"library_entry_id"`
	ChapterID      int64     `json:"chapter_id"`
	Progress       float64   `json:"progress"`
	Completed      bool      `json:"completed"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type Repository struct {
	ID           int64          `json:"id"`
	IndexUrl     string         `json:"index_url"`
	Name         sql.NullString `json:"name"`
	ContentType  string         `json:"content_type"`
	AddedAt      time.Time      `json:"added_at"`
	LastSyncedAt sql.NullTime   `json:"last_synced_at"`
}

type TrackerAccount struct {
	ID           int64          `json:"id"`
	TrackerType  string         `json:"tracker_type"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
}

type TrackerLink struct {
	ID                int64        `json:"id"`
	LibraryEntryID    int64        `json:"library_entry_id"`
	TrackerAccountID  int64        `json:"tracker_account_id"`
	ExternalTrackerID string       `json:"external_tracker_id"`
	SyncProgress      bool         `json:"sync_progress"`
	LastSyncedAt      sql.NullTime `json:"last_synced_at"`
}
