// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type AnimeEpisodeStream struct {
	ChapterID int64          `json:"chapter_id"`
	StreamUrl sql.NullString `json:"stream_url"`
	LocalPath sql.NullString `json:"local_path"`
}

type AppSetting struct {
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Chapter struct {
	ID          int64           `json:"id"`
	MediaID     int64           `json:"media_id"`
	ExternalID  string          `json:"external_id"`
	Title       sql.NullString  `json:"title"`
	Number      sql.NullFloat64 `json:"number"`
	UploadedAt  sql.NullInt64   `json:"uploaded_at"`
	SourceOrder sql.NullInt64   `json:"source_order"`
	FirstSeenAt sql.NullTime    `json:"first_seen_at"`
	Scanlator   string          `json:"scanlator"`
}

type Download struct {
	ID              int64           `json:"id"`
	ChapterID       int64           `json:"chapter_id"`
	Status          string          `json:"status"`
	Progress        float64         `json:"progress"`
	DownloadedBytes sql.NullInt64   `json:"downloaded_bytes"`
	BytesPerSec     sql.NullFloat64 `json:"bytes_per_sec"`
	Position        sql.NullInt64   `json:"position"`
	Error           sql.NullString  `json:"error"`
	CreatedAt       time.Time       `json:"created_at"`
	CompletedAt     sql.NullTime    `json:"completed_at"`
}

type Extension struct {
	ID               int64          `json:"id"`
	RepositoryID     int64          `json:"repository_id"`
	PackageName      string         `json:"package_name"`
	Name             string         `json:"name"`
	Version          string         `json:"version"`
	ContentType      string         `json:"content_type"`
	Lang             string         `json:"lang"`
	IconUrl          sql.NullString `json:"icon_url"`
	IconLocalPath    sql.NullString `json:"icon_local_path"`
	ApkUrl           string         `json:"apk_url"`
	JarUrl           sql.NullString `json:"jar_url"`
	JarPath          sql.NullString `json:"jar_path"`
	Installed        bool           `json:"installed"`
	Enabled          bool           `json:"enabled"`
	DiscoveredAt     time.Time      `json:"discovered_at"`
	InstalledAt      sql.NullTime   `json:"installed_at"`
	InstalledVersion sql.NullString `json:"installed_version"`
	NeedsUpdate      sql.NullBool   `json:"needs_update"`
	IsNsfw           bool           `json:"is_nsfw"`
	SupportsLatest   bool           `json:"supports_latest"`
}

type Folder struct {
	ID                int64          `json:"id"`
	Name              string         `json:"name"`
	Kind              string         `json:"kind"`
	SystemKey         sql.NullString `json:"system_key"`
	ParentFolderID    sql.NullInt64  `json:"parent_folder_id"`
	SortOrder         int64          `json:"sort_order"`
	CreatedAt         time.Time      `json:"created_at"`
	IncludeInUpdate   int64          `json:"include_in_update"`
	IncludeInDownload int64          `json:"include_in_download"`
}

type Genre struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type MangaPage struct {
	ChapterID  int64          `json:"chapter_id"`
	PageNumber int64          `json:"page_number"`
	LocalPath  sql.NullString `json:"local_path"`
}

type MediaFolder struct {
	MediaID  int64     `json:"media_id"`
	FolderID int64     `json:"folder_id"`
	AddedAt  time.Time `json:"added_at"`
}

type MediaGenre struct {
	MediaID int64 `json:"media_id"`
	GenreID int64 `json:"genre_id"`
}

type MediaTag struct {
	MediaID int64 `json:"media_id"`
	TagID   int64 `json:"tag_id"`
}

type Medium struct {
	ID                 int64          `json:"id"`
	ExtensionID        sql.NullInt64  `json:"extension_id"`
	ExtensionName      string         `json:"extension_name"`
	ExternalID         string         `json:"external_id"`
	ContentType        string         `json:"content_type"`
	Title              string         `json:"title"`
	CoverPath          sql.NullString `json:"cover_path"`
	CoverLocalPath     sql.NullString `json:"cover_local_path"`
	Description        sql.NullString `json:"description"`
	Status             sql.NullString `json:"status"`
	Author             sql.NullString `json:"author"`
	Artist             sql.NullString `json:"artist"`
	ExtensionRemovedAt sql.NullTime   `json:"extension_removed_at"`
	AddedAt            sql.NullTime   `json:"added_at"`
	LastViewedAt       sql.NullTime   `json:"last_viewed_at"`
	DetailsFetchedAt   sql.NullTime   `json:"details_fetched_at"`
	UpdatedAt          time.Time      `json:"updated_at"`
	ChaptersSyncedAt   sql.NullTime   `json:"chapters_synced_at"`
	CoverOverride      sql.NullString `json:"cover_override"`
}

type MetadataLink struct {
	ID          int64     `json:"id"`
	MediaID     int64     `json:"media_id"`
	Provider    string    `json:"provider"`
	ProviderID  string    `json:"provider_id"`
	ProviderUrl string    `json:"provider_url"`
	Confidence  float64   `json:"confidence"`
	Locked      int64     `json:"locked"`
	MatchedAt   time.Time `json:"matched_at"`
	CoverUrl    string    `json:"cover_url"`
}

type NovelChapterContent struct {
	ChapterID int64          `json:"chapter_id"`
	LocalPath sql.NullString `json:"local_path"`
}

type ReadingProgress struct {
	ID              int64           `json:"id"`
	MediaID         int64           `json:"media_id"`
	ChapterID       int64           `json:"chapter_id"`
	Progress        float64         `json:"progress"`
	Completed       bool            `json:"completed"`
	PositionSeconds sql.NullFloat64 `json:"position_seconds"`
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
	UpdatedAt       time.Time       `json:"updated_at"`
}

type Repository struct {
	ID           int64          `json:"id"`
	IndexUrl     string         `json:"index_url"`
	Name         sql.NullString `json:"name"`
	ContentType  string         `json:"content_type"`
	AddedAt      time.Time      `json:"added_at"`
	LastSyncedAt sql.NullTime   `json:"last_synced_at"`
}

type Tag struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type TrackerAccount struct {
	ID           int64          `json:"id"`
	TrackerType  string         `json:"tracker_type"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	Username     string         `json:"username"`
	ScoreFormat  string         `json:"score_format"`
}

type TrackerLink struct {
	ID                int64          `json:"id"`
	MediaID           int64          `json:"media_id"`
	TrackerAccountID  int64          `json:"tracker_account_id"`
	ExternalTrackerID string         `json:"external_tracker_id"`
	SyncProgress      bool           `json:"sync_progress"`
	LastSyncedAt      sql.NullTime   `json:"last_synced_at"`
	LibraryID         sql.NullString `json:"library_id"`
	TrackerTitle      string         `json:"tracker_title"`
	RemoteUrl         string         `json:"remote_url"`
	Status            int64          `json:"status"`
	LastChapterRead   float64        `json:"last_chapter_read"`
	TotalChapters     int64          `json:"total_chapters"`
	Score             float64        `json:"score"`
	StartedAt         sql.NullTime   `json:"started_at"`
	FinishedAt        sql.NullTime   `json:"finished_at"`
	Private           int64          `json:"private"`
}
