// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
	"database/sql"
)

type Querier interface {
	AddGenreToMedia(ctx context.Context, arg AddGenreToMediaParams) error
	AddMediaToFolder(ctx context.Context, arg AddMediaToFolderParams) error
	AddMediaToLibrary(ctx context.Context, id int64) (Medium, error)
	AddTagToMedia(ctx context.Context, arg AddTagToMediaParams) error
	ClearDownloads(ctx context.Context) error
	ClearDownloadsByStatus(ctx context.Context, statuses []string) error
	ClearExtensionIconPaths(ctx context.Context) error
	ClearGenresForMedia(ctx context.Context, mediaID int64) error
	ClearMediaCoverPaths(ctx context.Context) error
	CompleteDownload(ctx context.Context, id int64) error
	CountChaptersByMediaIDs(ctx context.Context, mediaIds []int64) ([]CountChaptersByMediaIDsRow, error)
	CountDownloadedChaptersByMediaIDs(ctx context.Context, mediaIds []int64) ([]CountDownloadedChaptersByMediaIDsRow, error)
	CountDownloadedPagesByChapterIDs(ctx context.Context, chapterIds []int64) ([]CountDownloadedPagesByChapterIDsRow, error)
	CountDownloadsByStatus(ctx context.Context) ([]CountDownloadsByStatusRow, error)
	CountExtensions(ctx context.Context, arg CountExtensionsParams) (int64, error)
	CountUnreadChaptersByMediaIDs(ctx context.Context, mediaIds []int64) ([]CountUnreadChaptersByMediaIDsRow, error)
	CreateChapter(ctx context.Context, arg CreateChapterParams) (Chapter, error)
	CreateFolder(ctx context.Context, arg CreateFolderParams) (Folder, error)
	CreateGenre(ctx context.Context, name string) (Genre, error)
	CreateLocalMedia(ctx context.Context, arg CreateLocalMediaParams) (Medium, error)
	CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error)
	CreateTag(ctx context.Context, name string) (Tag, error)
	DeleteAnimeEpisodeStream(ctx context.Context, chapterID int64) error
	DeleteDownload(ctx context.Context, id int64) error
	DeleteDownloadByChapter(ctx context.Context, chapterID int64) error
	DeleteDownloadsByChapters(ctx context.Context, chapterIds []int64) error
	DeleteFolder(ctx context.Context, id int64) error
	DeleteGenre(ctx context.Context, id int64) error
	DeleteMangaPage(ctx context.Context, arg DeleteMangaPageParams) error
	DeleteMangaPages(ctx context.Context, chapterID int64) error
	DeleteMetadataLink(ctx context.Context, arg DeleteMetadataLinkParams) error
	DeleteNovelChapterContent(ctx context.Context, chapterID int64) error
	DeleteRepository(ctx context.Context, id int64) error
	DeleteTag(ctx context.Context, id int64) error
	DeleteTrackerAccountByType(ctx context.Context, trackerType string) error
	DeleteTrackerLink(ctx context.Context, id int64) error
	EnqueueDownload(ctx context.Context, chapterID int64) (Download, error)
	FailDownload(ctx context.Context, arg FailDownloadParams) error
	GapFillMediaMetadata(ctx context.Context, arg GapFillMediaMetadataParams) (Medium, error)
	GetAnimeEpisodeStream(ctx context.Context, chapterID int64) (AnimeEpisodeStream, error)
	GetChapter(ctx context.Context, id int64) (Chapter, error)
	GetChapterByMediaAndExternalID(ctx context.Context, arg GetChapterByMediaAndExternalIDParams) (Chapter, error)
	GetChapterDownloadContext(ctx context.Context, id int64) (GetChapterDownloadContextRow, error)
	GetExtension(ctx context.Context, id int64) (Extension, error)
	GetExtensionByPackageName(ctx context.Context, packageName string) (Extension, error)
	GetExtensionsByIDs(ctx context.Context, ids []int64) ([]Extension, error)
	GetFolder(ctx context.Context, id int64) (Folder, error)
	GetFolderBySystemKey(ctx context.Context, systemKey sql.NullString) (Folder, error)
	GetLatestDownloadForChapter(ctx context.Context, chapterID int64) (Download, error)
	GetLatestDownloadsByChapterIDs(ctx context.Context, chapterIds []int64) ([]Download, error)
	GetLocalMediaByExternalID(ctx context.Context, externalID string) (Medium, error)
	GetMedia(ctx context.Context, id int64) (Medium, error)
	GetMediaByExtensionAndExternalID(ctx context.Context, arg GetMediaByExtensionAndExternalIDParams) (Medium, error)
	GetMetadataLink(ctx context.Context, arg GetMetadataLinkParams) (MetadataLink, error)
	GetNovelChapterContent(ctx context.Context, chapterID int64) (NovelChapterContent, error)
	GetQueuedDownloadByChapter(ctx context.Context, chapterID int64) (Download, error)
	GetRepository(ctx context.Context, id int64) (Repository, error)
	GetRepositoryByURL(ctx context.Context, indexUrl string) (Repository, error)
	GetTrackerAccount(ctx context.Context, trackerType string) (TrackerAccount, error)
	GetTrackerLink(ctx context.Context, id int64) (TrackerLink, error)
	LatestChapterByMediaIDs(ctx context.Context, mediaIds []int64) ([]Chapter, error)
	ListAllDownloads(ctx context.Context) ([]ListAllDownloadsRow, error)
	ListAllEpisodeStreamPaths(ctx context.Context) ([]ListAllEpisodeStreamPathsRow, error)
	ListAllMangaPagePaths(ctx context.Context) ([]MangaPage, error)
	ListAllNovelContentPaths(ctx context.Context) ([]NovelChapterContent, error)
	ListChapterExternalIDsByMedia(ctx context.Context, mediaID int64) ([]string, error)
	ListChapterUpdates(ctx context.Context, arg ListChapterUpdatesParams) ([]ListChapterUpdatesRow, error)
	ListChaptersByMedia(ctx context.Context, mediaID int64) ([]Chapter, error)
	ListChaptersMissingNumber(ctx context.Context) ([]ListChaptersMissingNumberRow, error)
	ListCompletedChapterTitles(ctx context.Context, mediaID int64) ([]ListCompletedChapterTitlesRow, error)
	ListDownloadedEpisodeStreamsByChapterIDs(ctx context.Context, chapterIds []int64) ([]ListDownloadedEpisodeStreamsByChapterIDsRow, error)
	ListDownloadedNovelContentByChapterIDs(ctx context.Context, chapterIds []int64) ([]NovelChapterContent, error)
	ListExtensionLanguages(ctx context.Context, arg ListExtensionLanguagesParams) ([]string, error)
	ListExtensionsByRepository(ctx context.Context, repositoryID int64) ([]Extension, error)
	ListFolders(ctx context.Context) ([]Folder, error)
	ListFoldersByMediaIDs(ctx context.Context, mediaIds []int64) ([]ListFoldersByMediaIDsRow, error)
	ListGenres(ctx context.Context) ([]Genre, error)
	ListGenresByMediaIDs(ctx context.Context, mediaIds []int64) ([]ListGenresByMediaIDsRow, error)
	ListGenresForMedia(ctx context.Context, mediaID int64) ([]Genre, error)
	ListInstalledExtensions(ctx context.Context) ([]Extension, error)
	ListLocalMedia(ctx context.Context) ([]Medium, error)
	ListMangaPages(ctx context.Context, chapterID int64) ([]MangaPage, error)
	ListMediaByIDs(ctx context.Context, ids []int64) ([]Medium, error)
	ListMediaForGenre(ctx context.Context, genreID int64) ([]Medium, error)
	ListMediaForTag(ctx context.Context, tagID int64) ([]Medium, error)
	ListMediaIDsWithTrackerLinks(ctx context.Context) ([]int64, error)
	ListMediaIDsWithoutMetadataLink(ctx context.Context) ([]int64, error)
	ListMediaInFolder(ctx context.Context, folderID int64) ([]Medium, error)
	ListMetadataLinksByMedia(ctx context.Context, mediaID int64) ([]MetadataLink, error)
	ListMetadataLinksByMediaIDs(ctx context.Context, mediaIds []int64) ([]MetadataLink, error)
	ListQueuedDownloads(ctx context.Context) ([]Download, error)
	ListReadingProgressByChapterIDs(ctx context.Context, chapterIds []int64) ([]ReadingProgress, error)
	ListReadingProgressByMedia(ctx context.Context, mediaID int64) ([]ReadingProgress, error)
	ListReadingProgressByMediaIDs(ctx context.Context, mediaIds []int64) ([]ReadingProgress, error)
	ListRecentChapters(ctx context.Context, arg ListRecentChaptersParams) ([]ListRecentChaptersRow, error)
	ListRepositories(ctx context.Context) ([]Repository, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTagsByMediaIDs(ctx context.Context, mediaIds []int64) ([]ListTagsByMediaIDsRow, error)
	ListTagsForMedia(ctx context.Context, mediaID int64) ([]Tag, error)
	ListTrackerAccounts(ctx context.Context) ([]TrackerAccount, error)
	ListTrackerLinksByMedia(ctx context.Context, mediaID int64) ([]TrackerLink, error)
	ListTrackerLinksByMediaIDs(ctx context.Context, mediaIds []int64) ([]TrackerLink, error)
	ListUpdateTargetMediaIDs(ctx context.Context) ([]int64, error)
	MarkChaptersReadUpToNumber(ctx context.Context, arg MarkChaptersReadUpToNumberParams) error
	MarkChaptersSynced(ctx context.Context, id int64) error
	MarkExtensionInstalled(ctx context.Context, arg MarkExtensionInstalledParams) (Extension, error)
	MarkExtensionUninstalled(ctx context.Context, id int64) (Extension, error)
	MarkExtensionUpdated(ctx context.Context, arg MarkExtensionUpdatedParams) (Extension, error)
	MarkMediaExtensionRemoved(ctx context.Context, extensionID sql.NullInt64) error
	MaxReadChapterNumber(ctx context.Context, mediaID int64) (float64, error)
	NextUnreadChapterByMediaIDs(ctx context.Context, mediaIds []int64) ([]Chapter, error)
	QueryExtensions(ctx context.Context, arg QueryExtensionsParams) ([]Extension, error)
	RemoveGenreFromMedia(ctx context.Context, arg RemoveGenreFromMediaParams) error
	RemoveMediaFromFolder(ctx context.Context, arg RemoveMediaFromFolderParams) error
	RemoveMediaFromFoldersByKind(ctx context.Context, arg RemoveMediaFromFoldersByKindParams) error
	RemoveMediaFromLibrary(ctx context.Context, id int64) (Medium, error)
	RemoveTagFromMedia(ctx context.Context, arg RemoveTagFromMediaParams) error
	RenameFolder(ctx context.Context, arg RenameFolderParams) (Folder, error)
	RequeueOrphanedDownloads(ctx context.Context) error
	RetryDownload(ctx context.Context, id int64) (Download, error)
	SetChapterNumber(ctx context.Context, arg SetChapterNumberParams) error
	SetDownloadPosition(ctx context.Context, arg SetDownloadPositionParams) error
	SetExtensionEnabled(ctx context.Context, arg SetExtensionEnabledParams) (Extension, error)
	SetFolderSortOrder(ctx context.Context, arg SetFolderSortOrderParams) (Folder, error)
	SetMediaCoverOverride(ctx context.Context, arg SetMediaCoverOverrideParams) (Medium, error)
	TouchMediaViewed(ctx context.Context, id int64) error
	TouchRepositorySync(ctx context.Context, id int64) error
	UpdateDownloadProgress(ctx context.Context, arg UpdateDownloadProgressParams) error
	UpdateDownloadStats(ctx context.Context, arg UpdateDownloadStatsParams) error
	UpdateExtensionIconLocalPath(ctx context.Context, arg UpdateExtensionIconLocalPathParams) error
	UpdateExtensionSupportsLatest(ctx context.Context, arg UpdateExtensionSupportsLatestParams) (Extension, error)
	UpdateFolderFlags(ctx context.Context, arg UpdateFolderFlagsParams) (Folder, error)
	UpdateLocalMedia(ctx context.Context, arg UpdateLocalMediaParams) (Medium, error)
	UpdateMediaCoverLocalPath(ctx context.Context, arg UpdateMediaCoverLocalPathParams) error
	UpdateRepositoryName(ctx context.Context, arg UpdateRepositoryNameParams) (Repository, error)
	UpsertAnimeEpisodeStream(ctx context.Context, arg UpsertAnimeEpisodeStreamParams) error
	UpsertExtension(ctx context.Context, arg UpsertExtensionParams) (Extension, error)
	UpsertMangaPage(ctx context.Context, arg UpsertMangaPageParams) error
	UpsertMediaBare(ctx context.Context, arg UpsertMediaBareParams) (Medium, error)
	UpsertMediaDetails(ctx context.Context, arg UpsertMediaDetailsParams) (Medium, error)
	UpsertMetadataLink(ctx context.Context, arg UpsertMetadataLinkParams) (MetadataLink, error)
	UpsertNovelChapterContent(ctx context.Context, arg UpsertNovelChapterContentParams) error
	UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error)
	UpsertTrackerAccount(ctx context.Context, arg UpsertTrackerAccountParams) (TrackerAccount, error)
	UpsertTrackerLink(ctx context.Context, arg UpsertTrackerLinkParams) (TrackerLink, error)
}

var _ Querier = (*Queries)(nil)
