// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_progress.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getReadingProgress = `-- name: GetReadingProgress :one
SELECT id, library_entry_id, chapter_id, progress, completed, updated_at, position_seconds, duration_seconds FROM reading_progress WHERE library_entry_id = ? AND chapter_id = ?
`

type GetReadingProgressParams struct {
	LibraryEntryID int64 `json:"library_entry_id"`
	ChapterID      int64 `json:"chapter_id"`
}

func (q *Queries) GetReadingProgress(ctx context.Context, arg GetReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, getReadingProgress, arg.LibraryEntryID, arg.ChapterID)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.LibraryEntryID,
		&i.ChapterID,
		&i.Progress,
		&i.Completed,
		&i.UpdatedAt,
		&i.PositionSeconds,
		&i.DurationSeconds,
	)
	return i, err
}

const listReadingProgressByLibraryEntry = `-- name: ListReadingProgressByLibraryEntry :many
SELECT id, library_entry_id, chapter_id, progress, completed, updated_at, position_seconds, duration_seconds FROM reading_progress WHERE library_entry_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListReadingProgressByLibraryEntry(ctx context.Context, libraryEntryID int64) ([]ReadingProgress, error) {
	rows, err := q.db.QueryContext(ctx, listReadingProgressByLibraryEntry, libraryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.LibraryEntryID,
			&i.ChapterID,
			&i.Progress,
			&i.Completed,
			&i.UpdatedAt,
			&i.PositionSeconds,
			&i.DurationSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one
INSERT INTO reading_progress (library_entry_id, chapter_id, progress, completed, position_seconds, duration_seconds)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(library_entry_id, chapter_id) DO UPDATE SET
    progress = excluded.progress,
    completed = excluded.completed,
    position_seconds = excluded.position_seconds,
    duration_seconds = excluded.duration_seconds,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, library_entry_id, chapter_id, progress, completed, updated_at, position_seconds, duration_seconds
`

type UpsertReadingProgressParams struct {
	LibraryEntryID  int64           `json:"library_entry_id"`
	ChapterID       int64           `json:"chapter_id"`
	Progress        float64         `json:"progress"`
	Completed       bool            `json:"completed"`
	PositionSeconds sql.NullFloat64 `json:"position_seconds"`
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertReadingProgress,
		arg.LibraryEntryID,
		arg.ChapterID,
		arg.Progress,
		arg.Completed,
		arg.PositionSeconds,
		arg.DurationSeconds,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.LibraryEntryID,
		&i.ChapterID,
		&i.Progress,
		&i.Completed,
		&i.UpdatedAt,
		&i.PositionSeconds,
		&i.DurationSeconds,
	)
	return i, err
}
