// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reading_progress.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"strings"
)

const listCompletedChapterTitles = `-- name: ListCompletedChapterTitles :many

SELECT c.number, c.title
FROM reading_progress rp
JOIN chapters c ON c.id = rp.chapter_id
WHERE rp.media_id = ? AND rp.completed = 1
`

type ListCompletedChapterTitlesRow struct {
	Number sql.NullFloat64 `json:"number"`
	Title  sql.NullString  `json:"title"`
}

func (q *Queries) ListCompletedChapterTitles(ctx context.Context, mediaID int64) ([]ListCompletedChapterTitlesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedChapterTitles, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompletedChapterTitlesRow{}
	for rows.Next() {
		var i ListCompletedChapterTitlesRow
		if err := rows.Scan(&i.Number, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingProgressByChapterIDs = `-- name: ListReadingProgressByChapterIDs :many

SELECT id, media_id, chapter_id, progress, completed, position_seconds, duration_seconds, updated_at FROM reading_progress
WHERE chapter_id IN (/*SLICE:chapter_ids*/?)
`

func (q *Queries) ListReadingProgressByChapterIDs(ctx context.Context, chapterIds []int64) ([]ReadingProgress, error) {
	query := listReadingProgressByChapterIDs
	var queryParams []interface{}
	if len(chapterIds) > 0 {
		for _, v := range chapterIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:chapter_ids*/?", strings.Repeat(",?", len(chapterIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:chapter_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.ChapterID,
			&i.Progress,
			&i.Completed,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingProgressByMedia = `-- name: ListReadingProgressByMedia :many
SELECT id, media_id, chapter_id, progress, completed, position_seconds, duration_seconds, updated_at FROM reading_progress WHERE media_id = ? ORDER BY updated_at DESC
`

func (q *Queries) ListReadingProgressByMedia(ctx context.Context, mediaID int64) ([]ReadingProgress, error) {
	rows, err := q.db.QueryContext(ctx, listReadingProgressByMedia, mediaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.ChapterID,
			&i.Progress,
			&i.Completed,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReadingProgressByMediaIDs = `-- name: ListReadingProgressByMediaIDs :many

SELECT id, media_id, chapter_id, progress, completed, position_seconds, duration_seconds, updated_at FROM reading_progress
WHERE media_id IN (/*SLICE:media_ids*/?)
ORDER BY media_id, updated_at DESC
`

func (q *Queries) ListReadingProgressByMediaIDs(ctx context.Context, mediaIds []int64) ([]ReadingProgress, error) {
	query := listReadingProgressByMediaIDs
	var queryParams []interface{}
	if len(mediaIds) > 0 {
		for _, v := range mediaIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:media_ids*/?", strings.Repeat(",?", len(mediaIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:media_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReadingProgress{}
	for rows.Next() {
		var i ReadingProgress
		if err := rows.Scan(
			&i.ID,
			&i.MediaID,
			&i.ChapterID,
			&i.Progress,
			&i.Completed,
			&i.PositionSeconds,
			&i.DurationSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markChaptersReadUpToNumber = `-- name: MarkChaptersReadUpToNumber :exec

INSERT INTO reading_progress (media_id, chapter_id, progress, completed)
SELECT ?1, c.id, 1.0, TRUE
FROM chapters c
WHERE c.media_id = ?1
  AND c.number > 0 AND c.number <= ?2
ON CONFLICT(media_id, chapter_id) DO UPDATE SET
    completed = TRUE, progress = 1.0, updated_at = CURRENT_TIMESTAMP
WHERE reading_progress.completed = 0
`

type MarkChaptersReadUpToNumberParams struct {
	MediaID int64           `json:"media_id"`
	UpTo    sql.NullFloat64 `json:"up_to"`
}

func (q *Queries) MarkChaptersReadUpToNumber(ctx context.Context, arg MarkChaptersReadUpToNumberParams) error {
	_, err := q.db.ExecContext(ctx, markChaptersReadUpToNumber, arg.MediaID, arg.UpTo)
	return err
}

const maxReadChapterNumber = `-- name: MaxReadChapterNumber :one

SELECT CAST(COALESCE(MAX(c.number), 0) AS REAL) AS max_number
FROM reading_progress rp
JOIN chapters c ON c.id = rp.chapter_id
WHERE rp.media_id = ? AND rp.completed = 1
`

func (q *Queries) MaxReadChapterNumber(ctx context.Context, mediaID int64) (float64, error) {
	row := q.db.QueryRowContext(ctx, maxReadChapterNumber, mediaID)
	var max_number float64
	err := row.Scan(&max_number)
	return max_number, err
}

const upsertReadingProgress = `-- name: UpsertReadingProgress :one
INSERT INTO reading_progress (media_id, chapter_id, progress, completed, position_seconds, duration_seconds)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(media_id, chapter_id) DO UPDATE SET
    progress = excluded.progress,
    completed = excluded.completed,
    position_seconds = excluded.position_seconds,
    duration_seconds = excluded.duration_seconds,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, media_id, chapter_id, progress, completed, position_seconds, duration_seconds, updated_at
`

type UpsertReadingProgressParams struct {
	MediaID         int64           `json:"media_id"`
	ChapterID       int64           `json:"chapter_id"`
	Progress        float64         `json:"progress"`
	Completed       bool            `json:"completed"`
	PositionSeconds sql.NullFloat64 `json:"position_seconds"`
	DurationSeconds sql.NullFloat64 `json:"duration_seconds"`
}

func (q *Queries) UpsertReadingProgress(ctx context.Context, arg UpsertReadingProgressParams) (ReadingProgress, error) {
	row := q.db.QueryRowContext(ctx, upsertReadingProgress,
		arg.MediaID,
		arg.ChapterID,
		arg.Progress,
		arg.Completed,
		arg.PositionSeconds,
		arg.DurationSeconds,
	)
	var i ReadingProgress
	err := row.Scan(
		&i.ID,
		&i.MediaID,
		&i.ChapterID,
		&i.Progress,
		&i.Completed,
		&i.PositionSeconds,
		&i.DurationSeconds,
		&i.UpdatedAt,
	)
	return i, err
}
