// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: repositories.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createRepository = `-- name: CreateRepository :one
INSERT INTO repositories (index_url, name, content_type)
VALUES (?, ?, ?)
RETURNING id, index_url, name, content_type, added_at, last_synced_at
`

type CreateRepositoryParams struct {
	IndexUrl    string         `json:"index_url"`
	Name        sql.NullString `json:"name"`
	ContentType string         `json:"content_type"`
}

func (q *Queries) CreateRepository(ctx context.Context, arg CreateRepositoryParams) (Repository, error) {
	row := q.db.QueryRowContext(ctx, createRepository, arg.IndexUrl, arg.Name, arg.ContentType)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.IndexUrl,
		&i.Name,
		&i.ContentType,
		&i.AddedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const deleteRepository = `-- name: DeleteRepository :exec
DELETE FROM repositories WHERE id = ?
`

func (q *Queries) DeleteRepository(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteRepository, id)
	return err
}

const getRepository = `-- name: GetRepository :one
SELECT id, index_url, name, content_type, added_at, last_synced_at FROM repositories WHERE id = ?
`

func (q *Queries) GetRepository(ctx context.Context, id int64) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepository, id)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.IndexUrl,
		&i.Name,
		&i.ContentType,
		&i.AddedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const getRepositoryByURL = `-- name: GetRepositoryByURL :one
SELECT id, index_url, name, content_type, added_at, last_synced_at FROM repositories WHERE index_url = ?
`

func (q *Queries) GetRepositoryByURL(ctx context.Context, indexUrl string) (Repository, error) {
	row := q.db.QueryRowContext(ctx, getRepositoryByURL, indexUrl)
	var i Repository
	err := row.Scan(
		&i.ID,
		&i.IndexUrl,
		&i.Name,
		&i.ContentType,
		&i.AddedAt,
		&i.LastSyncedAt,
	)
	return i, err
}

const listRepositories = `-- name: ListRepositories :many
SELECT id, index_url, name, content_type, added_at, last_synced_at FROM repositories ORDER BY added_at
`

func (q *Queries) ListRepositories(ctx context.Context) ([]Repository, error) {
	rows, err := q.db.QueryContext(ctx, listRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Repository{}
	for rows.Next() {
		var i Repository
		if err := rows.Scan(
			&i.ID,
			&i.IndexUrl,
			&i.Name,
			&i.ContentType,
			&i.AddedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchRepositorySync = `-- name: TouchRepositorySync :exec
UPDATE repositories SET last_synced_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchRepositorySync(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchRepositorySync, id)
	return err
}
