// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tags.sql

package sqlcgen

import (
	"context"
)

const addTagToEntry = `-- name: AddTagToEntry :exec
INSERT INTO library_entry_tags (library_entry_id, tag_id) VALUES (?, ?)
ON CONFLICT DO NOTHING
`

type AddTagToEntryParams struct {
	LibraryEntryID int64 `json:"library_entry_id"`
	TagID          int64 `json:"tag_id"`
}

func (q *Queries) AddTagToEntry(ctx context.Context, arg AddTagToEntryParams) error {
	_, err := q.db.ExecContext(ctx, addTagToEntry, arg.LibraryEntryID, arg.TagID)
	return err
}

const createTag = `-- name: CreateTag :one
INSERT INTO tags (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name = excluded.name
RETURNING id, name, created_at
`

func (q *Queries) CreateTag(ctx context.Context, name string) (Tag, error) {
	row := q.db.QueryRowContext(ctx, createTag, name)
	var i Tag
	err := row.Scan(&i.ID, &i.Name, &i.CreatedAt)
	return i, err
}

const deleteTag = `-- name: DeleteTag :exec
DELETE FROM tags WHERE id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const listEntriesForTag = `-- name: ListEntriesForTag :many
SELECT le.id, le.extension_id, le.extension_name, le.external_id, le.content_type, le.title, le.cover_path, le.description, le.status, le.extension_removed_at, le.added_at FROM library_entries le
JOIN library_entry_tags let ON let.library_entry_id = le.id
WHERE let.tag_id = ?
ORDER BY le.added_at DESC
`

func (q *Queries) ListEntriesForTag(ctx context.Context, tagID int64) ([]LibraryEntry, error) {
	rows, err := q.db.QueryContext(ctx, listEntriesForTag, tagID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LibraryEntry{}
	for rows.Next() {
		var i LibraryEntry
		if err := rows.Scan(
			&i.ID,
			&i.ExtensionID,
			&i.ExtensionName,
			&i.ExternalID,
			&i.ContentType,
			&i.Title,
			&i.CoverPath,
			&i.Description,
			&i.Status,
			&i.ExtensionRemovedAt,
			&i.AddedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTags = `-- name: ListTags :many
SELECT id, name, created_at FROM tags ORDER BY name
`

func (q *Queries) ListTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTagsForEntry = `-- name: ListTagsForEntry :many
SELECT t.id, t.name, t.created_at FROM tags t
JOIN library_entry_tags let ON let.tag_id = t.id
WHERE let.library_entry_id = ?
ORDER BY t.name
`

func (q *Queries) ListTagsForEntry(ctx context.Context, libraryEntryID int64) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, listTagsForEntry, libraryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(&i.ID, &i.Name, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeTagFromEntry = `-- name: RemoveTagFromEntry :exec
DELETE FROM library_entry_tags WHERE library_entry_id = ? AND tag_id = ?
`

type RemoveTagFromEntryParams struct {
	LibraryEntryID int64 `json:"library_entry_id"`
	TagID          int64 `json:"tag_id"`
}

func (q *Queries) RemoveTagFromEntry(ctx context.Context, arg RemoveTagFromEntryParams) error {
	_, err := q.db.ExecContext(ctx, removeTagFromEntry, arg.LibraryEntryID, arg.TagID)
	return err
}
