// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trackers.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createTrackerLink = `-- name: CreateTrackerLink :one
INSERT INTO tracker_links (library_entry_id, tracker_account_id, external_tracker_id, sync_progress)
VALUES (?, ?, ?, ?)
ON CONFLICT(library_entry_id, tracker_account_id) DO UPDATE SET
    external_tracker_id = excluded.external_tracker_id,
    sync_progress = excluded.sync_progress
RETURNING id, library_entry_id, tracker_account_id, external_tracker_id, sync_progress, last_synced_at
`

type CreateTrackerLinkParams struct {
	LibraryEntryID    int64  `json:"library_entry_id"`
	TrackerAccountID  int64  `json:"tracker_account_id"`
	ExternalTrackerID string `json:"external_tracker_id"`
	SyncProgress      bool   `json:"sync_progress"`
}

func (q *Queries) CreateTrackerLink(ctx context.Context, arg CreateTrackerLinkParams) (TrackerLink, error) {
	row := q.db.QueryRowContext(ctx, createTrackerLink,
		arg.LibraryEntryID,
		arg.TrackerAccountID,
		arg.ExternalTrackerID,
		arg.SyncProgress,
	)
	var i TrackerLink
	err := row.Scan(
		&i.ID,
		&i.LibraryEntryID,
		&i.TrackerAccountID,
		&i.ExternalTrackerID,
		&i.SyncProgress,
		&i.LastSyncedAt,
	)
	return i, err
}

const deleteTrackerAccount = `-- name: DeleteTrackerAccount :exec
DELETE FROM tracker_accounts WHERE id = ?
`

func (q *Queries) DeleteTrackerAccount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackerAccount, id)
	return err
}

const deleteTrackerLink = `-- name: DeleteTrackerLink :exec
DELETE FROM tracker_links WHERE id = ?
`

func (q *Queries) DeleteTrackerLink(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTrackerLink, id)
	return err
}

const getTrackerAccount = `-- name: GetTrackerAccount :one
SELECT id, tracker_type, access_token, refresh_token, expires_at FROM tracker_accounts WHERE tracker_type = ?
`

func (q *Queries) GetTrackerAccount(ctx context.Context, trackerType string) (TrackerAccount, error) {
	row := q.db.QueryRowContext(ctx, getTrackerAccount, trackerType)
	var i TrackerAccount
	err := row.Scan(
		&i.ID,
		&i.TrackerType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
	)
	return i, err
}

const getTrackerLink = `-- name: GetTrackerLink :one
SELECT id, library_entry_id, tracker_account_id, external_tracker_id, sync_progress, last_synced_at FROM tracker_links WHERE library_entry_id = ? AND tracker_account_id = ?
`

type GetTrackerLinkParams struct {
	LibraryEntryID   int64 `json:"library_entry_id"`
	TrackerAccountID int64 `json:"tracker_account_id"`
}

func (q *Queries) GetTrackerLink(ctx context.Context, arg GetTrackerLinkParams) (TrackerLink, error) {
	row := q.db.QueryRowContext(ctx, getTrackerLink, arg.LibraryEntryID, arg.TrackerAccountID)
	var i TrackerLink
	err := row.Scan(
		&i.ID,
		&i.LibraryEntryID,
		&i.TrackerAccountID,
		&i.ExternalTrackerID,
		&i.SyncProgress,
		&i.LastSyncedAt,
	)
	return i, err
}

const listTrackerAccounts = `-- name: ListTrackerAccounts :many
SELECT id, tracker_type, access_token, refresh_token, expires_at FROM tracker_accounts
`

func (q *Queries) ListTrackerAccounts(ctx context.Context) ([]TrackerAccount, error) {
	rows, err := q.db.QueryContext(ctx, listTrackerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackerAccount{}
	for rows.Next() {
		var i TrackerAccount
		if err := rows.Scan(
			&i.ID,
			&i.TrackerType,
			&i.AccessToken,
			&i.RefreshToken,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackerLinksByLibraryEntry = `-- name: ListTrackerLinksByLibraryEntry :many
SELECT id, library_entry_id, tracker_account_id, external_tracker_id, sync_progress, last_synced_at FROM tracker_links WHERE library_entry_id = ?
`

func (q *Queries) ListTrackerLinksByLibraryEntry(ctx context.Context, libraryEntryID int64) ([]TrackerLink, error) {
	rows, err := q.db.QueryContext(ctx, listTrackerLinksByLibraryEntry, libraryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TrackerLink{}
	for rows.Next() {
		var i TrackerLink
		if err := rows.Scan(
			&i.ID,
			&i.LibraryEntryID,
			&i.TrackerAccountID,
			&i.ExternalTrackerID,
			&i.SyncProgress,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTrackerLinkSync = `-- name: TouchTrackerLinkSync :exec
UPDATE tracker_links SET last_synced_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchTrackerLinkSync(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, touchTrackerLinkSync, id)
	return err
}

const upsertTrackerAccount = `-- name: UpsertTrackerAccount :one
INSERT INTO tracker_accounts (tracker_type, access_token, refresh_token, expires_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(tracker_type) DO UPDATE SET
    access_token = excluded.access_token,
    refresh_token = excluded.refresh_token,
    expires_at = excluded.expires_at
RETURNING id, tracker_type, access_token, refresh_token, expires_at
`

type UpsertTrackerAccountParams struct {
	TrackerType  string         `json:"tracker_type"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
}

func (q *Queries) UpsertTrackerAccount(ctx context.Context, arg UpsertTrackerAccountParams) (TrackerAccount, error) {
	row := q.db.QueryRowContext(ctx, upsertTrackerAccount,
		arg.TrackerType,
		arg.AccessToken,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	var i TrackerAccount
	err := row.Scan(
		&i.ID,
		&i.TrackerType,
		&i.AccessToken,
		&i.RefreshToken,
		&i.ExpiresAt,
	)
	return i, err
}
