// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Chapter struct {
	ID             string     `json:"id"`
	LibraryEntryID string     `json:"libraryEntryId"`
	ExternalID     string     `json:"externalId"`
	Title          *string    `json:"title,omitempty"`
	Number         *float64   `json:"number,omitempty"`
	UploadedAt     *time.Time `json:"uploadedAt,omitempty"`
}

type Extension struct {
	ID               string      `json:"id"`
	RepositoryID     string      `json:"repositoryId"`
	PackageName      string      `json:"packageName"`
	Name             string      `json:"name"`
	Version          string      `json:"version"`
	ContentType      ContentType `json:"contentType"`
	Lang             string      `json:"lang"`
	IconURL          *string     `json:"iconUrl,omitempty"`
	ApkURL           *string     `json:"apkUrl,omitempty"`
	JarURL           *string     `json:"jarUrl,omitempty"`
	JarPath          *string     `json:"jarPath,omitempty"`
	Installed        bool        `json:"installed"`
	Enabled          bool        `json:"enabled"`
	DiscoveredAt     time.Time   `json:"discoveredAt"`
	InstalledAt      *time.Time  `json:"installedAt,omitempty"`
	InstalledVersion *string     `json:"installedVersion,omitempty"`
	NeedsUpdate      *bool       `json:"needsUpdate,omitempty"`
}

type LibraryEntry struct {
	ID                 string             `json:"id"`
	ExtensionID        *string            `json:"extensionId,omitempty"`
	ExtensionName      string             `json:"extensionName"`
	ExternalID         string             `json:"externalId"`
	ContentType        ContentType        `json:"contentType"`
	Title              string             `json:"title"`
	CoverPath          *string            `json:"coverPath,omitempty"`
	Description        *string            `json:"description,omitempty"`
	Status             *string            `json:"status,omitempty"`
	ExtensionRemovedAt *time.Time         `json:"extensionRemovedAt,omitempty"`
	AddedAt            time.Time          `json:"addedAt"`
	Chapters           []*Chapter         `json:"chapters"`
	ReadingProgress    []*ReadingProgress `json:"readingProgress"`
}

type Mutation struct {
}

type Query struct {
}

type ReadingProgress struct {
	ID              string    `json:"id"`
	LibraryEntryID  string    `json:"libraryEntryId"`
	ChapterID       string    `json:"chapterId"`
	Progress        float64   `json:"progress"`
	Completed       bool      `json:"completed"`
	PositionSeconds *float64  `json:"positionSeconds,omitempty"`
	DurationSeconds *float64  `json:"durationSeconds,omitempty"`
	UpdatedAt       time.Time `json:"updatedAt"`
}

type Repository struct {
	ID           string      `json:"id"`
	IndexURL     string      `json:"indexUrl"`
	Name         *string     `json:"name,omitempty"`
	ContentType  ContentType `json:"contentType"`
	AddedAt      time.Time   `json:"addedAt"`
	LastSyncedAt *time.Time  `json:"lastSyncedAt,omitempty"`
}

type SearchResponse struct {
	Results     []*SearchResult `json:"results"`
	HasNextPage bool            `json:"hasNextPage"`
}

type SearchResult struct {
	SourceEntryID string  `json:"sourceEntryId"`
	Title         string  `json:"title"`
	CoverURL      *string `json:"coverUrl,omitempty"`
}

type SourceDetails struct {
	SourceEntryID string  `json:"sourceEntryId"`
	Title         string  `json:"title"`
	Description   *string `json:"description,omitempty"`
	CoverURL      *string `json:"coverUrl,omitempty"`
	Status        *string `json:"status,omitempty"`
}

type ContentType string

const (
	ContentTypeNovel ContentType = "NOVEL"
	ContentTypeManga ContentType = "MANGA"
	ContentTypeAnime ContentType = "ANIME"
)

var AllContentType = []ContentType{
	ContentTypeNovel,
	ContentTypeManga,
	ContentTypeAnime,
}

func (e ContentType) IsValid() bool {
	switch e {
	case ContentTypeNovel, ContentTypeManga, ContentTypeAnime:
		return true
	}
	return false
}

func (e ContentType) String() string {
	return string(e)
}

func (e *ContentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ContentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ContentType", str)
	}
	return nil
}

func (e ContentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ContentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ContentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
