package config

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"github.com/BurntSushi/toml"
)

type Config struct {
	DataDir           string
	HTTPAddr          string
	DBPath            string
	JarCacheDir       string
	MediaDir          string
	SandboxJarPath    string
	SandboxAddr       string
	SandboxPort       int
	SandboxExtDir     string
	SandboxStorageDir string
	SandboxHeapMB     int
	APIToken          string
	PprofAddr         string

	NovelEnabled         bool
	MetadataBackfill     bool
	IdleTimeoutMin       int
	TrackerPollHours     int
	PublicURL            string
	AniListClientID      string
	MALClientID          string
	MALClientSecret      string
	CloudflareSolverMode string
	CloudflareSolverURL  string
	ContentFilterLevel   string
}

func (c *Config) IdleTimeout() time.Duration {
	if c.IdleTimeoutMin <= 0 {
		return 0
	}
	return time.Duration(c.IdleTimeoutMin) * time.Minute
}

func Defaults() Config {
	return Config{
		HTTPAddr:             ":6007",
		DBPath:               "tsunagu.db",
		JarCacheDir:          "jar-cache",
		MediaDir:             "media",
		SandboxJarPath:       "sandbox.jar",
		SandboxAddr:          "localhost:50051",
		SandboxPort:          50051,
		SandboxExtDir:        "sandbox/extensions",
		SandboxStorageDir:    "data/plugin-storage",
		NovelEnabled:         true,
		MetadataBackfill:     true,
		IdleTimeoutMin:       15,
		TrackerPollHours:     6,
		PublicURL:            "http://localhost:6007",
		AniListClientID:      "49724",
		MALClientID:          "611c821aee93c5e51411bfa86ca32597",
		CloudflareSolverMode: "disabled",
		CloudflareSolverURL:  "http://127.0.0.1:8191",
		ContentFilterLevel:   "moderate",
	}
}

type Options struct {
	ConfigPath string
	DataDir    string
}

// Load reads tsunagu.toml (creating it from the template if absent) and returns
// the bootstrap-resolved config, the resolved toml path, and the set of keys
// that appeared as active (uncommented) lines in the file.
func Load(opts Options) (*Config, string, map[string]bool, error) {
	c := Defaults()
	if opts.DataDir != "" {
		c.DataDir = opts.DataDir
	}

	path := opts.ConfigPath
	if path == "" {
		if c.DataDir != "" {
			path = filepath.Join(c.DataDir, "tsunagu.toml")
		} else {
			path = "tsunagu.toml"
		}
	}

	active := map[string]bool{}
	raw, err := os.ReadFile(path)
	switch {
	case err == nil:
		var m map[string]any
		if err := toml.Unmarshal(raw, &m); err != nil {
			return nil, "", nil, fmt.Errorf("parse %s: %w", path, err)
		}
		for _, s := range settings {
			v, ok := m[s.Key]
			if !ok {
				continue
			}
			active[s.Key] = true
			if err := s.set(&c, toString(v)); err != nil {
				return nil, "", nil, fmt.Errorf("%s in %s: %w", s.Key, path, err)
			}
		}
	case os.IsNotExist(err):
		// regenerated by the Store after Sync; nothing to read yet.
	default:
		return nil, "", nil, err
	}

	c.applyDataDir(active)
	return &c, path, active, nil
}

func (c *Config) applyDataDir(active map[string]bool) {
	if c.DataDir == "" {
		return
	}
	root := func(key, def, name string, dst *string) {
		if !active[key] && *dst == def {
			*dst = filepath.Join(c.DataDir, name)
		}
	}
	root("db_path", "tsunagu.db", "tsunagu.db", &c.DBPath)
	root("jar_cache_dir", "jar-cache", "jar-cache", &c.JarCacheDir)
	root("media_dir", "media", "media", &c.MediaDir)
	root("sandbox_extensions_dir", "sandbox/extensions", "extensions", &c.SandboxExtDir)
	root("sandbox_storage_dir", "data/plugin-storage", "plugin-storage", &c.SandboxStorageDir)
}

func toString(v any) string {
	switch t := v.(type) {
	case string:
		return t
	case bool:
		if t {
			return "true"
		}
		return "false"
	case int64:
		return fmt.Sprintf("%d", t)
	case float64:
		return fmt.Sprintf("%g", t)
	default:
		return fmt.Sprint(v)
	}
}
